version: '3'
volumes:
  postgres_data:
      driver: local
services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      restart: always
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
         # Descomentar abaixo para usar ssl no banco
        #JDBC_PARAMS: "ssl=true"
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - postgres

